// Re-export from global constants for backward compatibility
export {
  DEFAULT_VOICE_STABILITY,
  DEFAULT_VOICE_SIMILARITY_BOOST,
  DEFAULT_VOICE_STYLE,
  DEFAULT_USE_SPEAKER_BOOST,
  TTS_PROVIDERS,
  DEFAULT_TTS_PROVIDER,
  AUDIO_OUTPUT_FORMAT,
  AUDIO_SAMPLE_RATE,
  AUDIO_BIT_RATE,
  MAX_AUDIO_GENERATIONS_PER_DAY,
  MAX_AUDIO_GENERATIONS_PER_HOUR,
  AUDIO_CACHE_TTL,
  AUDIO_VERSION_START,
  MAX_AUDIO_VERSIONS_PER_NARRATION,
} from '@constants/audioConsts.js';

export type { TTSProvider } from '@constants/audioConsts.js';
