import {
  GenreType,
  ToneType,
  IntensityCurve,
  NarrationProfile,
} from "@models/ContextProfile.js";

export const NARRATION_PROFILES: Record<GenreType, NarrationProfile> = {
  [GenreType.HORROR]: {
    wordsPerSecond: 2.1,
    minWordTolerance: 10,
    maxWordTolerance: 10,
    pauseBias: "high",
    sentenceLengthBias: "short",
    clauseDensity: "sparse",
    tone: ToneType.DARK,
    emotionBias: "subtle",
    intensityCurve: IntensityCurve.SLOW_BURN,
  },

  [GenreType.PSYCHOLOGICAL_HORROR]: {
    wordsPerSecond: 2.0,
    minWordTolerance: 12,
    maxWordTolerance: 12,
    pauseBias: "high",
    sentenceLengthBias: "short",
    clauseDensity: "sparse",
    tone: ToneType.SOMBER,
    emotionBias: "subtle",
    intensityCurve: IntensityCurve.RISING,
  },

  [GenreType.THRILLER]: {
    wordsPerSecond: 2.8,
    minWordTolerance: 8,
    maxWordTolerance: 8,
    pauseBias: "low",
    sentenceLengthBias: "very-short",
    clauseDensity: "balanced",
    tone: ToneType.GRITTY,
    emotionBias: "expressive",
    intensityCurve: IntensityCurve.PULSED,
  },

  [GenreType.CRIME]: {
    wordsPerSecond: 2.6,
    minWordTolerance: 8,
    maxWordTolerance: 8,
    pauseBias: "low",
    sentenceLengthBias: "short",
    clauseDensity: "dense",
    tone: ToneType.GRITTY,
    emotionBias: "flat",
    intensityCurve: IntensityCurve.PULSED,
  },

  [GenreType.NOIR]: {
    wordsPerSecond: 2.2,
    minWordTolerance: 10,
    maxWordTolerance: 10,
    pauseBias: "medium",
    sentenceLengthBias: "medium",
    clauseDensity: "balanced",
    tone: ToneType.BLEAK,
    emotionBias: "flat",
    intensityCurve: IntensityCurve.FLAT,
  },

  [GenreType.SCIFI]: {
    wordsPerSecond: 3.0,
    minWordTolerance: 12,
    maxWordTolerance: 12,
    pauseBias: "none",
    sentenceLengthBias: "medium",
    clauseDensity: "dense",
    tone: ToneType.NEUTRAL,
    emotionBias: "flat",
    intensityCurve: IntensityCurve.FLAT,
  },

  [GenreType.HARD_SCIFI]: {
    wordsPerSecond: 3.2,
    minWordTolerance: 14,
    maxWordTolerance: 14,
    pauseBias: "none",
    sentenceLengthBias: "long",
    clauseDensity: "dense",
    tone: ToneType.NEUTRAL,
    emotionBias: "flat",
    intensityCurve: IntensityCurve.FLAT,
  },

  [GenreType.FANTASY]: {
    wordsPerSecond: 2.4,
    minWordTolerance: 15,
    maxWordTolerance: 15,
    pauseBias: "medium",
    sentenceLengthBias: "long",
    clauseDensity: "balanced",
    tone: ToneType.EPIC,
    emotionBias: "subtle",
    intensityCurve: IntensityCurve.RISING,
  },

  [GenreType.DARK_FANTASY]: {
    wordsPerSecond: 2.3,
    minWordTolerance: 14,
    maxWordTolerance: 14,
    pauseBias: "medium",
    sentenceLengthBias: "long",
    clauseDensity: "balanced",
    tone: ToneType.DARK,
    emotionBias: "subtle",
    intensityCurve: IntensityCurve.SLOW_BURN,
  },

  [GenreType.DRAMA]: {
    wordsPerSecond: 2.0,
    minWordTolerance: 10,
    maxWordTolerance: 10,
    pauseBias: "high",
    sentenceLengthBias: "medium",
    clauseDensity: "balanced",
    tone: ToneType.INTIMATE,
    emotionBias: "expressive",
    intensityCurve: IntensityCurve.FLAT,
  },

  [GenreType.MYSTERY]: {
    wordsPerSecond: 2.3,
    minWordTolerance: 10,
    maxWordTolerance: 10,
    pauseBias: "medium",
    sentenceLengthBias: "short",
    clauseDensity: "balanced",
    tone: ToneType.SOMBER,
    emotionBias: "subtle",
    intensityCurve: IntensityCurve.RISING,
  },

  [GenreType.ROMANCE]: {
    wordsPerSecond: 2.2,
    minWordTolerance: 12,
    maxWordTolerance: 12,
    pauseBias: "medium",
    sentenceLengthBias: "long",
    clauseDensity: "balanced",
    tone: ToneType.INTIMATE,
    emotionBias: "expressive",
    intensityCurve: IntensityCurve.FLAT,
  },

  [GenreType.ADVENTURE]: {
    wordsPerSecond: 2.7,
    minWordTolerance: 10,
    maxWordTolerance: 10,
    pauseBias: "low",
    sentenceLengthBias: "medium",
    clauseDensity: "balanced",
    tone: ToneType.EPIC,
    emotionBias: "expressive",
    intensityCurve: IntensityCurve.PULSED,
  },

  [GenreType.POST_APOCALYPTIC]: {
    wordsPerSecond: 2.0,
    minWordTolerance: 14,
    maxWordTolerance: 14,
    pauseBias: "high",
    sentenceLengthBias: "short",
    clauseDensity: "sparse",
    tone: ToneType.BLEAK,
    emotionBias: "flat",
    intensityCurve: IntensityCurve.COLLAPSING,
  },
    [GenreType.CYBERPUNK]: {
    wordsPerSecond: 3.0,
    minWordTolerance: 10,
    maxWordTolerance: 10,
    pauseBias: "low",
    sentenceLengthBias: "short",
    clauseDensity: "dense",
    tone: ToneType.GRITTY,
    emotionBias: "flat",
    intensityCurve: IntensityCurve.PULSED,
  },

  [GenreType.HISTORICAL]: {
    wordsPerSecond: 2.2,
    minWordTolerance: 14,
    maxWordTolerance: 14,
    pauseBias: "medium",
    sentenceLengthBias: "long",
    clauseDensity: "dense",
    tone: ToneType.SOMBER,
    emotionBias: "subtle",
    intensityCurve: IntensityCurve.FLAT,
  },

  [GenreType.WAR]: {
    wordsPerSecond: 2.6,
    minWordTolerance: 12,
    maxWordTolerance: 12,
    pauseBias: "low",
    sentenceLengthBias: "short",
    clauseDensity: "balanced",
    tone: ToneType.GRITTY,
    emotionBias: "expressive",
    intensityCurve: IntensityCurve.SPIKING,
  },

  [GenreType.TRAGEDY]: {
    wordsPerSecond: 1.9,
    minWordTolerance: 16,
    maxWordTolerance: 16,
    pauseBias: "high",
    sentenceLengthBias: "long",
    clauseDensity: "sparse",
    tone: ToneType.BLEAK,
    emotionBias: "subtle",
    intensityCurve: IntensityCurve.COLLAPSING,
  },

};
